language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

env:
  - SYMFONY_VERSION=5.0.*

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  exclude:
    - php: 7.1
      env: SYMFONY_VERSION=5.0.*
    - php: 7.2
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*
    - php: 8.0
      env: SYMFONY_VERSION=5.0.*
    - php: 8.1
      env: SYMFONY_VERSION=6.0.*

before_install:
  - composer self-update
  - composer require -n --prefer-dist "symfony/symfony:${SYMFONY_VERSION}"

script:
  - php -v
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
